name: Composite_Flow-Test

on:
  workflow_dispatch:
  
env:
  GLOBAL_ENV_VAR: 'Firt Global variable' # This variable is available to all jobs
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use my composite action
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'
